---
title: "Basic Mathematics by R 6-7"
subtitle: "KGSOC「数理・データサイエンスのための基礎数学」参考資料"
author: "石田　淳 (aishida@kwansei.ac.jp)"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 6章　確率(1)

Rでコイン投げ（ベルヌイ試行）を行ってみよう．`sample`関数を使う方法といきなり`rbinom`関数を使う方法がある．ここでは`sample`を使おう．

```{r}
sample(c(0, 1), 1)
# sample(1:6,1) # サイコロ
rbinom(1, 1, 0.5)
```

10回投げて平均を取る（成功割合）．

```{r}
coins <- sample(c(0,1), 10, replace = TRUE)
# replicate(10, sample(c(0, 1), 1)))
coins
mean(coins)
```

10回投げて平均を取る操作を1000回行って平均のヒストグラムをとる．


```{r}
means <- replicate(1000,  mean(sample(c(0,1), 10, replace = TRUE)))
mean(means)
sd(means)
hist(means, col = "skyblue")
```

コイン投げ回数を1回ずつ増やしていってそのつど平均を取る．回数が多くなるにつれて，0.5に収束していっているようだ．

```{r}
coin_mean <- function(n) mean(sample(c(0,1), n, replace = TRUE))
mean_series <- sapply(1:500, coin_mean)
plot(1:500, mean_series, type = "l", col = "blue")
abline(h = 0.5, lty = "dashed", col = "black")
```

# 7章　確率(2)

二項分布を観察する．Rにはすでに基本的な分布の関数が入っている．

二項分布の確率関数は`dbinom(x, n, p)`である．

```{r}
dbinom(0:10, 10, 0.5)
sum(dbinom(0:10, 10, 0.5))
```

```{r}
plot(0:10, dbinom(0:10, 10, 0.5), pch = 19, 
     col = "blue", xlab = "", ylab = "")
for (i in 0:10) {
  lines(x = c(i, i), y = c(0, dbinom(i, 10, 0.5)),
        col = "blue")
}
```

```{r}
plot(0:10, dbinom(0:10, 10, 0.3), pch = 19, ylim = c(0, 0.275), 
     axes = FALSE, col = rgb(0,0,1,alpha = 0.5), xlab = "", ylab = "")
par(new = TRUE)
plot(0:10, dbinom(0:10, 10, 0.5), pch = 19, ylim = c(0, 0.275), 
     axes = FALSE, col = rgb(1,0,0,alpha = 0.5), xlab = "", ylab = "")
par(new = TRUE)
plot(0:10, dbinom(0:10, 10, 0.7), pch = 19, ylim = c(0, 0.275), 
     axes = TRUE, col = rgb(0,1,0,alpha = 0.5), xlab = "", ylab = "")
for (i in 0:10) {
  lines(x = c(i, i), y = c(0, dbinom(i, 10, 0.3)),
        col = rgb(0,0,1,alpha = 0.5))
}
for (i in 0:10) {
  lines(x = c(i, i), y = c(0, dbinom(i, 10, 0.5)),
        col = rgb(1,0,0,alpha = 0.5))
}
for (i in 0:10) {
  lines(x = c(i, i), y = c(0, dbinom(i, 10, 0.7)),
        col = rgb(0,1,0,alpha = 0.5))
}
```

二項分布にしたがう乱数を発生させる．

```{r}
freq <- rbinom(1000, 10, 0.5)
hist(freq, col = "skyblue")
```
