---
title: "Basic Mathematics by R 2-3"
subtitle: "2021年度KGSOC「数理・データサイエンスのための基礎数学」参考資料"
author: "石田　淳 (aishida@kwansei.ac.jp)"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2章　論理(1)

Rでは，TRUEとFALSEがブール値（真理値）である．`typeof()`関数で確認する．

```{r}
typeof(c(TRUE, FALSE))
```

## 論理和

論理和$p\lor q$はRでは`|`である．

```{r}
age <- 25
gender <- "F"

if (age >= 20 | gender == "M") {
  print("20歳以上もしくは男性")
} else {
  print("False")
}
```


```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
p_or_q <- p | q
cbind(p, q, p_or_q)
```

## 論理積

論理積$p\land q$は`&`である．

```{r}
age <- 25
gender <- "F"

if (age >= 20 & gender == "M") {
  print("20歳以上かつ男性")
} else {
  print("False")
}
```

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
p_and_q <- p & q
cbind(p,q,p_and_q)
```

## 否定

否定$\lnot$は`!`である．

```{r}
age <- 18

if (!(age >= 20)) {
  print("20歳以上でない")
} else {
  print("False")
}
```

```{r}
p <- c(TRUE, FALSE)
not_p <- !p
cbind(p,not_p)
```

p.11 式(2.4) $\neg p \lor \neg q$

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
not_p_or_not_q <- !p | !q
cbind(p,q,not_p_or_not_q)
```

## 条件式

条件式$\to$と同値の真理表

```{r}
cond <- function(p, q) !p | q
```

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
p_cond_q <- cond(p, q)
cbind(p,q,p_cond_q)
```

## 双条件式

双条件式$\leftrightarrow$と同値の真理表

```{r}
bicond <- function(p, q) (p & q) | (!p & !q)
```

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
p_bicond_q <- bicond(p, q)
cbind(p,q,p_bicond_q)
```

# 3章　論理(2)

## トートロジー

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
cond(p, p) # p -> p
cond(p, p | q) # p -> p or q
bicond(!(p & q), !p | !q) # not (p and q) <--> not p or not q
```

## 逆，裏，対偶

```{r}
p <- c(TRUE, TRUE, FALSE, FALSE)
q <- c(TRUE, FALSE, TRUE, FALSE)
cond(p, q) # p -> p
cond(q, p) # q -> p
cond(!p, !q) # not p -> not q
cond(!q, !p) # not p -> not q
```
