---
title: "Basic Mathematics by R 4-5"
subtitle: "KGSOC「数理・データサイエンスのための基礎数学」参考資料"
author: "石田　淳 (aishida@kwansei.ac.jp)"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 4-5章　集合(1-2)

Rのベクトル型を集合と見なして，基本的な集合演算ができる．

ただし，ベクトルなので重複を許容することに注意．ベクトルの重複を削りたい場合はunique関数を使う．

```{r}
A <- unique(c(1,1,2,3))
B <- c(1,2,3,4,5)
C <- c(3,4,5)
```

## 要素

$a \in A$

$B$の各要素は$A$の要素か．


```{r}
for (i in B) {
  print(paste(i, " in A is", is.element(i, A)))
}
```

## 部分集合

$A\subset B$

部分集合関係を見る場合，定義より`is.element`でのチェックをすべて行って，すべて`TRUE`の場合，部分集合と判断する関数を作る．

```{r}
subset <- function(X, Y) {
  all(sapply(X, function(x) is.element(x,Y)))
}

print(paste('A <= B is', subset(A,B)))
print(paste('C <= B is', subset(C,B)))
print(paste('A <= C is', subset(A,C)))
```

## 空集合

$\emptyset$

からベクトルで代用．

```{r}
EmpSet <- c()
print(paste('EmpSet <= A is', subset(EmpSet, A)))
```

## 和集合

$A \cup B$

`union`関数を用いる．

```{r}
print(paste(c('A cup B = {', union(A,B), '}'), collapse = " "))
print(paste(c('C cup B = {', union(C,B), '}'), collapse = " "))
print(paste(c('A cup C = {', union(A,C), '}'), collapse = " "))
```

## 積集合

$A \cap B$

`intersect`関数を用いる．

```{r}
print(paste(c('A cap B = {', intersect(A,B), '}'), collapse = " "))
print(paste(c('C cap B = {', intersect(C,B), '}'), collapse = " "))
print(paste(c('A cap C = {', intersect(A,C), '}'), collapse = " "))
```

## 補集合

$A^c$

`setdiff`関数を用いる．


```{r}
# Bを全体集合とする
print(paste(c('A^B = {', setdiff(B,A), '}'), collapse = " "))
print(paste(c('C^B = {', setdiff(B,C), '}'), collapse = " "))
```

集合演算のパッケージとしてはいくつかのものが公開されているようであるが，詳細は不明．
