---
title: "Basic Mathematics by R 10-11"
subtitle: "2021年度KGSOC「数理・データサイエンスのための基礎数学」参考資料"
author: "石田　淳 (aishida@kwansei.ac.jp)"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 10章　積分

`integrate()`関数を使った数値積分が可能である．

```{r}
f <- function(x) x^2
integrate(f, 0, 1)
```

不定積分（の近似）は`function(x) integrate(f,b,x)`という関数で定義すればよい．

```{r}
f <- function(x) x^2
F <- function(x) integrate(f,0,x)$value
plot(function(x) x^3/3,0,1,xlab="",ylab="")
par(new = T)
plot(cbind(seq(0,1,0.1),sapply(seq(0,1,0.1),F)),col="red",xlab="",ylab="")
```

標準正規分布のpdfの全範囲積分．

```{r}
stdnorm_pdf <- function(x) exp(-x^2/2)/sqrt(2*pi)
integrate(stdnorm_pdf, -Inf, Inf)
stdnorm_cdf <- function(x) integrate(stdnorm_pdf, -Inf, x)$value
plot(stdnorm_pdf,-3,3,xlim=c(-3,3),ylim=c(0,1),xlab="",ylab="")
par(new = T)
plot(cbind(seq(-3,3,0.1),sapply(seq(-3,3,0.1),stdnorm_cdf)),col="red"
     ,xlim=c(-3,3),ylim=c(0,1),xlab="",ylab="")
```

# 11章　指数と対数

指数関数
```{r}
x <- seq(-1,3,0.1)
plot(x, exp(x), type = "l")
```

対数関数
```{r}
x <- seq(0.1,3,0.1)
plot(x, log(x), type = "l")
```

二項分布のパラメータの最尤推定

```{r}
L <- function(p) dbinom(7,10,p)
p <- seq(0.01,0.99,0.01)
plot(p,L(p),type="l")
optimize(L, c(0,1),maximum = TRUE)
```

```{r}
logL <- function(p) log(dbinom(7,10,p))
plot(p,logL(p),type="l")
optimize(logL, c(0,1),maximum = TRUE)
```